### PR TITLE
add getProduct and getProducts methods

### PR DESCRIPTION
**Pull request by coyotebringsfire**
I refactored my original PR to put the code in the right places, and also use native Promises instead of Q.

Two methods are added to the BugzillaClient object: getProduct and getProducts. tests are also included in tests-basic.js

### CODE REVIEW

**Comment by canuckistani** [comment]
This looks like it should work but what I think is missing is you didn't run 'gulp' to regenerate build/node/index.js and build/browser/bz.js. All you should need to to is:

1. in the root directory, run 'gulp'
2. commit changes to the newly generated files

Once this is done the Travis tests should pass.

**Comment by canuckistani** [comment]
Aside: you don't need to open new PRs every time, just push to your branch.

**Comment by coyotebringsfire** [comment]
i didn't know if you wanted the generated files included in the PR, that's why I originally left them out. i've now added them to the PR

**Comment by canuckistani** [comment]
Yeah sorry it's implied - the tests need those files to run. And magically the tests pass!

**Pull request merged**
